# Generated by Django 4.2.7 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign',
            field=models.DateTimeField(),
        ),
    ]
