# Generated by Django 4.2.7 on 2023-12-07 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_task_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
